const fs = require("node:fs/promises");
const path = require("node:path");

module.exports = function redirectsPlugin(eleventyConfig) {
  let redirects = [];

  eleventyConfig.addCollection("redirects", (collectionApi) => {
    const redirectsBySource = new Map();

    for (const page of collectionApi.getAll()) {
      const sources = page.data.redirect_from;
      if (!sources) continue;

      for (const source of Array.isArray(sources) ? sources : [sources]) {
        const existingTarget = redirectsBySource.get(source);
        if (existingTarget && existingTarget !== page.url) {
          throw new Error(
            `Redirect ${source} points to both ${existingTarget} and ${page.url}`,
          );
        }
        redirectsBySource.set(source, page.url);
      }
    }

    redirects = [...redirectsBySource].map(([source, target]) => ({
      source,
      target,
    }));
    return redirects;
  });

  eleventyConfig.on("eleventy.after", async ({ dir }) => {
    if (!redirects.length) return;

    const contents = [
      "# Generated by the Eleventy redirects plugin",
      ...redirects.map(({ source, target }) => `${source} ${target} 301`),
      "",
    ].join("\n");

    await fs.writeFile(path.join(dir.output, "_redirects"), contents);
  });
};